
from product_data import product_catalog

def generate_proposal(client_type, issue):
    product_match = None
    for product, info in product_catalog.items():
        if any(word in issue.lower() for word in info['use'].split()):
            product_match = (product, info)
            break

    if not product_match:
        return "We couldn't find a direct match. A sales rep will contact you for a customized solution."

    name, info = product_match
    return f"""
# Proposal for {client_type} Client

Thank you for reaching out to Momar regarding: **{issue}**

Based on our analysis, we recommend using **{name}**. This product is ideal for {info['use']} and is safe for use on {info['surface']}.

### Application:
- Dilution: {info['dilution']}
- Notes: {info['note']}

This recommendation has been auto-generated by our AI assistant based on your description. For further details, contact your regional Momar expert.

Thank you for considering Momar — we’re here to solve your toughest maintenance challenges.
"""
